name: GitHub Profile 3D Contrib

on:
  # Runs daily at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Skyline
        uses: gumbobrot/github-profile-3d-contrib@0.7.2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Generated 3D Skyline" || echo "No changes to commit"
          git push
